FROM panos/hadoop

MAINTAINER Panayiotis Vlantis <panosv@di.uoa.gr>

WORKDIR /opt/hadoop

COPY entrypoint.sh /opt/hadoop/

EXPOSE 9000 50010 50020 50070 50075 50090

# ENTRYPOINT ["/opt/hadoop/entrypoint.sh"]
