version: '2'
services:

  spark_master:
    image: panos/spark
    entrypoint:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
    restart: always
    ports:
      - "4040"
      - "4041"
      - "4042"
      - "6066"
      - "7077"
      - "8080"
    hostname: master
    environment:
      - SPARK_PUBLIC_DNS=master

  spark_worker:
    image: panos/spark
    ports:
      - "8081"
    depends_on:
      - spark_master
    links:
      - spark_master:master
    entrypoint:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://master:7077
    restart: always
  
  zeppelin:
    image: panos/zeppelin
    restart: always
    depends_on:
      - spark_master
    links:
      - spark_master:master
    ports:
      - "8080:8080"
    environment:
      - "MASTER=spark://master:7077"


