version: '2'
services:

  spark_master:
    image: panos/spark
    command: org.apache.spark.deploy.master.Master
    ports:
      - "6066"
      - "7077"
      - "8080"
    hostname: master
    environment:
      - SPARK_PUBLIC_DNS=master

  spark_worker:
    image: panos/spark
    depends_on:
      - spark_master
    links:
      - spark_master:master
    command: org.apache.spark.deploy.worker.Worker spark://master:7077
  
  zeppelin:
    image: panos/zeppelin
    depends_on:
      - spark_master
    links:
      - spark_master:master
    ports:
      - "8080:58080"
    environment:
      - "MASTER=spark://master:7077"


